### PR TITLE
#161041391 Admin Login Dashboard (Feature)

### PR DESCRIPTION
**Pull request by bryan-munene**
**What does this PR do?**

This PR creates a login page for an admin user/Store Owner.

**Description of Task to be completed?**

For this PR, these are the tasks to be completed:
1. Provide textfields for the user to input their account login credentials, i.e. their email and their password.
2. Provide a button for the submission of the form
3. If correct redirect the user to their dashboard

**How should this be manually tested?**

This can be tested manually on gh-pages.

**Any background context you want to provide?**

This page is necessary to ensure only authorized users gain access to restricted sections of the app.

**What are the relevant pivotal tracker stories?**

#161041391

**Screenshots (if appropriate)**

admin signin

**Questions:**

### CODE REVIEW

**Comment by Etomovich** [comment]
Awesome work!! Keep Up the spirit

**Comment by bryan-munene** [comment]
> Awesome work!! Keep Up the spirit

Thanks

**Comment by bryanmwaniqi** [comment]
thats a dope ui

**Comment by bryan-munene** [comment]
> thats a dope ui

Thanks.

**Pull request merged**
